excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://tinypressco.github.io
title: TinyPress
tagline: TinyPress
description: The world's best GitHub blogging platform.
paginate: 5
